apiVersion: zadara.com/v1alpha1
kind: CloneConfiguration
metadata:
  name: dr-us-west-clone
spec:
  appSnapshot:
    # references to metadata.name of ApplicationSnapshot
    name: "mysql-snap-2020-01-26"
  dryRun: false
  prefix: "clone-"
  suffix: ""
  targetNamespace: "test"
