---
# This file is for debugging & reference purposes only.
# Actual CronJobs are created by Invoker for each (configuration, policy)
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-configuration-policy
  labels:
    snapshotConfiguration: configuration
    snapshotPolicy: policy
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  # Running Job of this CronJob will prevent new Jobs from starting
  concurrencyPolicy: Forbid
  # Do not start the Job if it misses scheduled time by startingDeadlineSeconds for any reason.
  # Optimally should be close to the interval of schedule.
  startingDeadlineSeconds: 120
  jobTemplate:
    metadata:
      labels:
        snapshotConfiguration: configuration
        snapshotPolicy: policy
    spec:
      # If Pod of the Job failed: Deadline Exceed (activeDeadlineSeconds), or Client errors,
      # it will run again up to backoffLimit times.
      backoffLimit: 1
      template:
        metadata:
          labels:
            snapshotConfiguration: configuration
            snapshotPolicy: policy
        spec:
          # Let Job controller manage Pod restarts
          restartPolicy: Never
          # Pod will be killed, if not completed in activeDeadlineSeconds
          activeDeadlineSeconds: 60
          serviceAccountName: zoperator
          containers:
          - name: zoperator-cronjob
            image: "zadara/zoperator:0.0.1"
            command:
              # note: this overrides ENTRYPOINT defined in Docker image
              - cronjob
            env:
              # Note: fieldRef's reference fields of the **Pod**, as the Pod knows nothing about it's owner
              - name: SNAPSHOT_CONFIGURATION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['snapshotConfiguration']
              - name: SNAPSHOT_POLICY
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['snapshotPolicy']
              - name: SNAPSHOT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            volumeMounts:
              - name: config-dir
                mountPath: /etc/zoperator
          volumes:
            - name: config-dir
              configMap:
                name: zoperator-config-map
