apiVersion: zadara.com/v1alpha1
kind: Vpsa
metadata:
  name: example-vpsa
spec:
  hostname: "example.vpsas.zadara.com"
  https: true
  token: "EXAMPLETOKEN-1234"
  # csi: if defined, run CSI driver and connect to VPSA
  csi:
    provisioner: "csi.zadara.com"
    iscsiMode: "rootfs"
    # Support VPSA Volume auto-expand feature
    autoExpandSupport: true
    # livenessProbe: k8s built-in, some fields omitted
    livenessProbe:
      periodSeconds: 5
      httpGet:
        port: 9808
